name: geos
description: A set of classes useful in geographical context.
version: 2.0.1
repository: https://github.com/Marco87Developer/geos
# homepage: https://www.example.com

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  collection: ^1.16.0
  meta: ^1.7.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

assets:
  - test/models/place_not_valid_1_test.json
  - test/models/place_not_valid_2_test.json
  - test/models/place_test.json
